# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 52151cfb6a4177c6572749ca718ce64072737de8b06924e4bfae3f73b21a50db9f5293420024e48e53953243a99f87efed4dded1965bd0f0201a64c8e5fbe7ff

test:
  secret_key_base: 6692030b4caab3b3e1f1b7376a90e38135e7189121ff60206ed217ec7198ba6bb04a259837b4de33f4c000751eaf4afd54052ec5b1748e0d7b3fb23a07a91ef6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
